name: iOS CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_26.0.1.app

    - name: Install dependencies
      run: bundle install

    - name: Build and Test
      run: |
        set -o pipefail
        xcodebuild test \
          -project DrinkTracker.xcodeproj \
          -scheme "DrinkTracker Dev" \
          -destination "platform=iOS Simulator,name=iPhone 17,OS=26.0" \
          -only-testing:DrinkTrackerTests \
          ENABLE_SWIFT_TESTING=YES \
          | xcpretty && exit ${PIPESTATUS[0]}
